version: '3.9'

# $ sudo docker-compose down -v --rmi local && sudo lsof -t -i:1025 | xargs kill -9 && sudo docker-compose up -d && sudo yarn typeorm migration:run && sudo docker logs rentx -f

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
